### ISSUE TITLE
How about my hardware?

### ISSUE THREAD

**Issue by DD885** [vncsmnl/EFI-HUANANZHI-X99-BD4-HACKINTOSH#2]
My Complete hardware specs is:

CPU：          	Intel Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Memory：         	Samsung 32GB DDR4 * 4
Display Card：         	RX6800XT
MainBoard：         	HUANANZHI-X99-BD4
Hard Disk Drive：       	KingBank KP230 Pro( 2TB,SSD )

How about my hardware specs work on this EFI?

**Comment by vncsmnl** [comment]
Yes, what matters is the motherboard
