### ISSUE TITLE
How about my hardware?

### ISSUE THREAD

**Issue by nuub228** [vncsmnl/EFI-HUANANZHI-X99-BD4-HACKINTOSH#3]
CPU:              Xeon e5 2640v3
Mainboard:   HUANANZHI X99 BD4
RAM:              KLLISRE 2x8gb DDR4 2666 NON-ECC
Videocard:    XFX rx470

**Comment by nuub228** [comment]
The difference between our components at first glance is not strong###

**Comment by vncsmnl** [comment]
Yes, what matters is the motherboard

**Comment by nuub228** [comment]
/
