### ISSUE TITLE
Please help 🙏🙏🙏 not start macOs image

### ISSUE THREAD

**Issue by Zabalkanskiy** [vncsmnl/EFI-HUANANZHI-X99-BD4-HACKINTOSH#7]
![IMG_20231021_195808](https://github.com/vncsmnl/EFI-HUANANZHI-X99-BD4-HACKINTOSH/assets/16476552/ccb0559b-cb9c-43b2-ab49-1fa02b83bc74)

I create usb for load macOs. Use gide https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html#downloading-macos

Remap Usbport and generate SmBios 
I put macOs image in com.apple.recovery.boot in usb
I add efi folder on usb
I load from usb and get  this screen. 

Please help me🙏🙏🙏

**Comment by Zabalkanskiy** [comment]
[EFI.zip](https://github.com/vncsmnl/EFI-HUANANZHI-X99-BD4-HACKINTOSH/files/13062621/EFI.zip)
my efi folder

**Comment by vncsmnl** [comment]
I don't do consultancy
