### ISSUE TITLE
Not work USB on front panel. Huananzhi X99 QD4 + E5-2667 v4

### ISSUE THREAD

**Issue by andrewinsidelazarev** [vncsmnl/EFI-HUANANZHI-X99-BD4-HACKINTOSH#8]

**Comment by andrewinsidelazarev** [comment]
All works well except USB on front panel

**Comment by vncsmnl** [comment]
This EFI is for BD4 motherboards, you shouldn't even use this EFI with the QD4. Make the USB Map for your motherboard

**Comment by andrewinsidelazarev** [comment]
Removed your USB Maps and added removed XhciPortLimit. And all USB are working now.
Maybe this is now beautiful way, but USB inject all kext + port mapping also is no beautiful way.
